# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-9831-ercole/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master /opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master {
      /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master/bcam_reg.v
      /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master/camctl.v
      /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master/iitcam9b.v
      /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master/iitram9b.v
      /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master/iitram9bx1k.v
      /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master/lpm_out.v
      /home/simone/iitcam_verilog/iitcam_verilog.srcs/sources_1/new/lutdram.v
      /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master/prefreg.v
      /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master/setram.v
      /home/simone/Indirectly-Indexed-2D-Ternary-Content-Addressable-Memory-TCAM-master/iitcam.v
    }
      rt::read_vhdl -lib xil_defaultlib /home/simone/iitcam_verilog/iitcam_verilog.srcs/sources_1/new/ram_mixed.vhd
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top iitcam
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-9831-ercole/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
